# Generated by Django 5.2.16 on 2026-07-16 13:27

import apps.properties.models
import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Property name")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "property_code",
                    models.CharField(db_index=True, default="GVC-001", max_length=30, unique=True),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("cottage_resort", "Cottage Resort"),
                            ("resort", "Resort"),
                            ("hotel", "Hotel"),
                            ("homestay", "Homestay"),
                            ("guest_house", "Guest House"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="cottage_resort",
                        max_length=30,
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                (
                    "short_description",
                    models.TextField(
                        blank=True,
                        help_text="Short description shown on property cards and headers.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Complete customer-facing property description."
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("locality", models.CharField(blank=True, db_index=True, max_length=120)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(db_index=True, default="Mount Abu", max_length=120)),
                ("district", models.CharField(blank=True, default="Sirohi", max_length=120)),
                ("state", models.CharField(db_index=True, default="Rajasthan", max_length=120)),
                ("country", models.CharField(default="India", max_length=120)),
                ("pincode", models.CharField(db_index=True, default="307501", max_length=12)),
                ("google_plus_code", models.CharField(blank=True, max_length=150)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("google_maps_url", models.URLField(blank=True, max_length=1000)),
                ("primary_phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("secondary_phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp_number", models.CharField(blank=True, db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("reservation_email", models.EmailField(blank=True, max_length=254)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                ("instagram_url", models.URLField(blank=True, max_length=500)),
                ("facebook_url", models.URLField(blank=True, max_length=500)),
                ("check_in_time", models.TimeField(default=datetime.time(12, 0))),
                ("check_out_time", models.TimeField(default=datetime.time(10, 0))),
                ("reception_open_time", models.TimeField(blank=True, null=True)),
                ("reception_close_time", models.TimeField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.properties.models.property_logo_upload_path,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.properties.models.property_thumbnail_upload_path,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.properties.models.property_cover_upload_path,
                    ),
                ),
                (
                    "exterior_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                (
                    "reception_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                (
                    "garden_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                (
                    "common_area_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                (
                    "facilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Property-level facilities such as parking, garden and Wi-Fi.",
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                (
                    "nearby_places",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_nearby_places],
                    ),
                ),
                (
                    "house_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                ("cancellation_policy", models.TextField(blank=True)),
                ("refund_policy", models.TextField(blank=True)),
                ("child_policy", models.TextField(blank=True)),
                ("pet_policy", models.TextField(blank=True)),
                ("extra_guest_policy", models.TextField(blank=True)),
                ("damage_policy", models.TextField(blank=True)),
                ("early_check_in_policy", models.TextField(blank=True)),
                ("late_check_out_policy", models.TextField(blank=True)),
                (
                    "minimum_check_in_age",
                    models.PositiveSmallIntegerField(
                        default=18, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("id_proof_required", models.BooleanField(default=True)),
                ("local_id_allowed", models.BooleanField(default=True)),
                ("unmarried_couples_allowed", models.BooleanField(default=True)),
                ("visitors_allowed", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=False)),
                ("smoking_allowed", models.BooleanField(default=False)),
                ("alcohol_allowed", models.BooleanField(default=False)),
                ("outside_food_allowed", models.BooleanField(default=True)),
                ("children_allowed", models.BooleanField(default=True)),
                (
                    "children_free_below_age",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("booking_enabled", models.BooleanField(db_index=True, default=True)),
                ("same_day_booking_allowed", models.BooleanField(default=True)),
                (
                    "minimum_stay_nights",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "maximum_stay_nights",
                    models.PositiveSmallIntegerField(
                        default=30, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "maximum_advance_booking_days",
                    models.PositiveIntegerField(
                        default=365, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("minimum_advance_booking_hours", models.PositiveIntegerField(default=0)),
                ("pay_at_property_allowed", models.BooleanField(default=True)),
                ("online_payment_enabled", models.BooleanField(default=False)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "default_tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("tax_included_in_price", models.BooleanField(default=False)),
                ("advance_payment_required", models.BooleanField(default=False)),
                (
                    "advance_payment_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("legal_business_name", models.CharField(blank=True, max_length=255)),
                ("gst_number", models.CharField(blank=True, max_length=20)),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                ("billing_address", models.TextField(blank=True)),
                ("invoice_prefix", models.CharField(default="GVC", max_length=20)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                (
                    "seo_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.properties.models.validate_string_list],
                    ),
                ),
                ("canonical_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("temporarily_closed", "Temporarily Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "db_table": "properties",
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["status", "booking_enabled"], name="property_public_idx"),
                    models.Index(fields=["city", "state"], name="property_location_idx"),
                    models.Index(fields=["created_at"], name="property_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("status",),
                        name="only_one_active_property",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minimum_stay_nights__gte", 1)),
                        name="property_min_stay_gte_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("maximum_stay_nights__gte", models.F("minimum_stay_nights"))
                        ),
                        name="property_max_stay_gte_min_stay",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_tax_percentage__gte", 0), ("default_tax_percentage__lte", 100)
                        ),
                        name="property_tax_between_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("advance_payment_percentage__gte", 0),
                            ("advance_payment_percentage__lte", 100),
                        ),
                        name="property_advance_between_0_100",
                    ),
                ],
            },
        ),
    ]
