# Generated by Django 5.2.16 on 2026-07-17 10:00

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="check_in_time",
            field=models.TimeField(default=apps.properties.models.default_check_in_time),
        ),
        migrations.AlterField(
            model_name="property",
            name="check_out_time",
            field=models.TimeField(default=apps.properties.models.default_check_out_time),
        ),
    ]
