# Generated by Django 5.2.16 on 2026-07-16 13:50

import apps.cottages.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cottage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("cottage_code", models.CharField(db_index=True, max_length=30, unique=True)),
                ("room_type", models.CharField(blank=True, max_length=100)),
                ("bed_type", models.CharField(blank=True, max_length=100)),
                ("short_description", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("location_note", models.CharField(blank=True, max_length=255)),
                ("view_type", models.CharField(blank=True, max_length=100)),
                (
                    "number_of_beds",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "number_of_bathrooms",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "maximum_guests",
                    models.PositiveSmallIntegerField(
                        default=2, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "maximum_adults",
                    models.PositiveSmallIntegerField(
                        default=2, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("maximum_children", models.PositiveSmallIntegerField(default=0)),
                ("extra_bed_available", models.BooleanField(default=False)),
                (
                    "base_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="Default Monday to Friday price.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "saturday_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saturday night price.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "sunday_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sunday night price.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "extra_adult_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "extra_child_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "minimum_nights",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.cottages.models.cottage_thumbnail_upload_path,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.cottages.models.cottage_cover_upload_path,
                    ),
                ),
                (
                    "bed_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.cottages.models.validate_string_list],
                    ),
                ),
                (
                    "bathroom_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.cottages.models.validate_string_list],
                    ),
                ),
                (
                    "interior_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.cottages.models.validate_string_list],
                    ),
                ),
                (
                    "exterior_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.cottages.models.validate_string_list],
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.cottages.models.validate_string_list],
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.cottages.models.validate_string_list],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cottages",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "cottages",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CottageAvailabilityHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_in_date", models.DateField(db_index=True)),
                ("check_out_date", models.DateField(db_index=True)),
                ("guest_phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("converted", "Converted to Booking"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cottage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_holds",
                        to="cottages.cottage",
                    ),
                ),
            ],
            options={
                "db_table": "cottage_availability_holds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CottageBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("repair", "Repair"),
                            ("cleaning", "Cleaning"),
                            ("private_use", "Private Use"),
                            ("renovation", "Renovation"),
                            ("other", "Other"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "cottage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="cottages.cottage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cottage_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cottage_blocks",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="cottage",
            index=models.Index(fields=["property"], name="cottage_property_idx"),
        ),
        migrations.AddIndex(
            model_name="cottage",
            index=models.Index(fields=["slug"], name="cottage_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="cottage",
            index=models.Index(fields=["cottage_code"], name="cottage_code_idx"),
        ),
        migrations.AddIndex(
            model_name="cottage",
            index=models.Index(fields=["status"], name="cottage_status_idx"),
        ),
        migrations.AddIndex(
            model_name="cottage",
            index=models.Index(fields=["is_featured"], name="cottage_featured_idx"),
        ),
        migrations.AddIndex(
            model_name="cottage",
            index=models.Index(fields=["base_price"], name="cottage_base_price_idx"),
        ),
        migrations.AddIndex(
            model_name="cottage",
            index=models.Index(fields=["status", "sort_order"], name="cottage_public_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="cottage",
            constraint=models.CheckConstraint(
                condition=models.Q(("maximum_guests__gte", 1)), name="cottage_guests_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="cottage",
            constraint=models.CheckConstraint(
                condition=models.Q(("maximum_adults__gte", 1)), name="cottage_adults_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="cottage",
            constraint=models.CheckConstraint(
                condition=models.Q(("maximum_guests__gte", models.F("maximum_adults"))),
                name="cottage_guests_gte_adults",
            ),
        ),
        migrations.AddConstraint(
            model_name="cottage",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gte", 0)), name="cottage_base_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="cottage",
            constraint=models.CheckConstraint(
                condition=models.Q(("saturday_price__gte", 0)), name="cottage_saturday_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="cottage",
            constraint=models.CheckConstraint(
                condition=models.Q(("sunday_price__gte", 0)), name="cottage_sunday_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="cottage",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_percentage__gte", 0), ("tax_percentage__lte", 100)),
                name="cottage_tax_between_0_100",
            ),
        ),
        migrations.AddIndex(
            model_name="cottageavailabilityhold",
            index=models.Index(
                fields=["cottage", "check_in_date", "check_out_date", "status"],
                name="cottage_hold_overlap_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cottageavailabilityhold",
            index=models.Index(fields=["expires_at", "status"], name="cottage_hold_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="cottageavailabilityhold",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out_date__gt", models.F("check_in_date"))),
                name="cottage_hold_checkout_after_checkin",
            ),
        ),
        migrations.AddIndex(
            model_name="cottageblock",
            index=models.Index(
                fields=["cottage", "start_date", "end_date"], name="cottage_block_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cottageblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="cottage_block_end_after_start",
            ),
        ),
    ]
