# Generated by Django 5.2.16 on 2026-07-25 12:04

import apps.cottages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cottages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cottage",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.cottages.models.cottage_cover_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="cottage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=apps.cottages.models.cottage_thumbnail_upload_path,
            ),
        ),
    ]
