# Generated by Django 5.2.16 on 2026-07-24 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DishType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: Indian, Chinese, Continental, Rajasthani",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "food_type",
                    models.CharField(
                        choices=[("veg", "Veg"), ("non_veg", "Non-Veg")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Food Categories",
                "ordering": ["display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "food_type"), name="unique_food_category_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "food_type",
                    models.CharField(
                        choices=[("veg", "Veg"), ("non_veg", "Non-Veg")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "full_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Regular or full portion price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "half_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional half portion price",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image_list",
                    models.JSONField(
                        blank=True, default=list, help_text="List of uploaded image URLs"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_items",
                        to="dining.foodcategory",
                    ),
                ),
                (
                    "dish_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_items",
                        to="dining.dishtype",
                    ),
                ),
            ],
            options={
                "ordering": ["category__display_order", "display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"), name="unique_food_item_per_category"
                    )
                ],
            },
        ),
    ]
