# Generated by Django 5.2.16 on 2026-07-17 09:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("pay_at_property", "Pay at Property"),
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online_gateway", "Online Gateway"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="successful",
                        max_length=25,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online_gateway", "Online Gateway"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, db_index=True, max_length=150)),
                ("gateway_order_id", models.CharField(blank=True, db_index=True, max_length=150)),
                ("gateway_payment_id", models.CharField(blank=True, db_index=True, max_length=150)),
                ("gateway_signature", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("notes", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "created_at"], name="payment_booking_created_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="payment_status_created_idx"
                    ),
                    models.Index(
                        fields=["method", "created_at"], name="payment_method_created_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="payment_amount_gt_zero"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("transaction_id", ""), _negated=True),
                        fields=("transaction_id",),
                        name="uniq_nonblank_payment_txn",
                    ),
                ],
            },
        ),
    ]
