# Generated by Django 5.2.16 on 2026-07-17 09:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("card", "Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("razorpay", "Razorpay"),
                    ("online_gateway", "Online Gateway"),
                ],
                db_index=True,
                default="manual",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("razorpay", "Razorpay"), ("upi_qr", "UPI QR")],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("attempted", "Attempted"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                ("receipt", models.CharField(db_index=True, max_length=40)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=150, null=True, unique=True),
                ),
                ("upi_vpa", models.CharField(blank=True, max_length=100)),
                ("upi_intent_url", models.TextField(blank=True)),
                ("qr_code_data_uri", models.TextField(blank=True)),
                ("provider_payload", models.JSONField(blank=True, default=dict)),
                ("notes", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_orders",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "payment_orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "provider", "status"],
                        name="payorder_booking_provider_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="payorder_status_created_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="payment_order_amount_gt_zero"
                    )
                ],
            },
        ),
    ]
