export interface PropertyNearbyPlace {
  name: string;
  category?: string;
  distance?: string;
  travel_time?: string;
  maps_url?: string;
}

export interface Property {
  id: string;
  name: string;
  slug: string;
  property_code: string;
  property_type: string;
  tagline: string;
  short_description: string;
  description: string;
  address_line_1: string;
  address_line_2: string;
  locality: string;
  landmark: string;
  city: string;
  district: string;
  state: string;
  country: string;
  pincode: string;
  google_plus_code: string;
  latitude: string | null;
  longitude: string | null;
  google_maps_url: string;
  primary_phone: string;
  secondary_phone: string;
  whatsapp_number: string;
  email: string;
  reservation_email: string;
  public_email: string;
  public_phone: string;
  website_url: string;
  instagram_url: string;
  facebook_url: string;
  check_in_time: string;
  check_out_time: string;
  reception_open_time: string | null;
  reception_close_time: string | null;
  logo: string | null;
  thumbnail: string | null;
  cover_image: string | null;
  exterior_images: string[];
  reception_images: string[];
  garden_images: string[];
  common_area_images: string[];
  gallery_images: string[];
  facilities: string[];
  nearby_places: PropertyNearbyPlace[];
  house_rules: string[];
  cancellation_policy: string;
  refund_policy: string;
  child_policy: string;
  pet_policy: string;
  extra_guest_policy: string;
  damage_policy: string;
  early_check_in_policy: string;
  late_check_out_policy: string;
  minimum_check_in_age: number;
  id_proof_required: boolean;
  local_id_allowed: boolean;
  unmarried_couples_allowed: boolean;
  visitors_allowed: boolean;
  pets_allowed: boolean;
  smoking_allowed: boolean;
  alcohol_allowed: boolean;
  outside_food_allowed: boolean;
  children_allowed: boolean;
  children_free_below_age: number;
  quiet_hours_start: string | null;
  quiet_hours_end: string | null;
  booking_enabled: boolean;
  same_day_booking_allowed: boolean;
  minimum_stay_nights: number;
  maximum_stay_nights: number;
  maximum_advance_booking_days: number;
  minimum_advance_booking_hours: number;
  pay_at_property_allowed: boolean;
  online_payment_enabled: boolean;
  currency: string;
  default_tax_percentage: string;
  tax_included_in_price: boolean;
  advance_payment_required: boolean;
  advance_payment_percentage: string;
  seo_title: string;
  seo_description: string;
  seo_keywords: string;
  canonical_url: string;
  status: "active" | "inactive";
  full_address: string;
  created_at: string;
  updated_at: string;
}
