# Generated by Django 5.2.16 on 2026-07-16 14:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cottages", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "booking_sequences",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking_id",
                    models.CharField(db_index=True, editable=False, max_length=25, unique=True),
                ),
                ("guest_name", models.CharField(db_index=True, max_length=150)),
                (
                    "guest_phone",
                    models.CharField(
                        db_index=True,
                        help_text="Store in international format, for example +919876543210.",
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number with country code, for example +919876543210.",
                                regex="^\\+?[1-9]\\d{7,14}$",
                            )
                        ],
                    ),
                ),
                ("guest_email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("guest_address", models.TextField(blank=True)),
                ("guest_city", models.CharField(blank=True, max_length=100)),
                ("guest_state", models.CharField(blank=True, max_length=100)),
                ("guest_country", models.CharField(blank=True, default="India", max_length=100)),
                ("guest_pincode", models.CharField(blank=True, max_length=12)),
                (
                    "id_proof_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aadhaar", "Aadhaar Card"),
                            ("pan", "PAN Card"),
                            ("passport", "Passport"),
                            ("driving_licence", "Driving Licence"),
                            ("voter_id", "Voter ID"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("id_proof_number", models.CharField(blank=True, max_length=100)),
                (
                    "id_proof_image",
                    models.ImageField(blank=True, null=True, upload_to="bookings/id-proofs/%Y/%m/"),
                ),
                ("check_in_date", models.DateField(db_index=True)),
                ("check_out_date", models.DateField(db_index=True)),
                (
                    "number_of_nights",
                    models.PositiveSmallIntegerField(
                        editable=False, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "adults",
                    models.PositiveSmallIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("expected_arrival_time", models.TimeField(blank=True, null=True)),
                ("weekday_nights", models.PositiveSmallIntegerField(default=0, editable=False)),
                ("saturday_nights", models.PositiveSmallIntegerField(default=0, editable=False)),
                ("sunday_nights", models.PositiveSmallIntegerField(default=0, editable=False)),
                (
                    "weekday_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "saturday_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "sunday_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "room_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=25,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("pay_at_property", "Pay at Property"),
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online_gateway", "Online Gateway"),
                        ],
                        db_index=True,
                        default="pay_at_property",
                        max_length=30,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, db_index=True, max_length=150)),
                (
                    "hold_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Pending bookings block availability only until this time.",
                        null=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=25,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("admin", "Admin"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("walk_in", "Walk-in"),
                        ],
                        db_index=True,
                        default="website",
                        max_length=20,
                    ),
                ),
                ("special_request", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("whatsapp_opt_in", models.BooleanField(default=True)),
                ("sms_opt_in", models.BooleanField(default=False)),
                ("email_opt_in", models.BooleanField(default=True)),
                (
                    "preferred_notification_channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("all", "All"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "cottage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="cottages.cottage",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "db_table": "bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_booking_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "new_booking_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "previous_payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "new_payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=25,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_status_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CancellationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "requested_phone",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number with country code, for example +919876543210.",
                                regex="^\\+?[1-9]\\d{7,14}$",
                            )
                        ],
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_requests",
                        to="bookings.booking",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_cancellation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_cancellation_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["cottage", "check_in_date", "check_out_date"],
                name="booking_cottage_dates_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["cottage", "booking_status"], name="booking_cottage_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_status", "check_in_date"], name="booking_status_checkin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_status", "check_out_date"], name="booking_status_checkout_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["guest_phone", "booking_id"], name="booking_phone_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_status", "created_at"], name="booking_payment_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["source", "created_at"], name="booking_source_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out_date__gt", models.F("check_in_date"))),
                name="booking_checkout_after_checkin",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("number_of_nights__gte", 1)), name="booking_nights_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("adults__gte", 1)), name="booking_adults_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("children__gte", 0)), name="booking_children_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("room_amount__gte", 0)), name="booking_room_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)), name="booking_subtotal_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="booking_tax_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)), name="booking_discount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("grand_total__gte", 0)), name="booking_total_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__gte", 0)), name="booking_paid_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_amount__gte", 0)), name="booking_balance_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__lte", models.F("grand_total"))),
                name="booking_paid_not_above_total",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatushistory",
            index=models.Index(
                fields=["booking", "created_at"], name="booking_history_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cancellationrequest",
            index=models.Index(fields=["status", "created_at"], name="cancel_request_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="cancellationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("booking",),
                name="one_pending_cancellation_per_booking",
            ),
        ),
    ]
