# Generated by Django 5.2.16 on 2026-07-17 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp"), ("sms", "SMS")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(db_index=True, max_length=255)),
                ("template_name", models.CharField(blank=True, db_index=True, max_length=100)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                ("provider_event_id", models.CharField(blank=True, db_index=True, max_length=150)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["booking", "created_at"], name="notif_booking_created_idx"
                    ),
                    models.Index(fields=["channel", "status"], name="notif_channel_status_idx"),
                    models.Index(fields=["status", "created_at"], name="notif_status_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_event_id", ""), _negated=True),
                        fields=("provider_event_id",),
                        name="uniq_nonblank_notif_event_id",
                    )
                ],
            },
        ),
    ]
